### ISSUE TITLE
GetDependenciesAsync throws exception 200, with a json parsing issue.

### ISSUE THREAD

**Issue by zylonity** [Zechiax/Modrinth.Net#117]
Pretty much what the title says. I was able to fix this by changing Line 16 of Dependencies.cs from System.Version[] to Models.Version[], not sure if it was intentional for it to be system.version in the first place

**Comment by zylonity** [comment]
Submitted pull request

**Comment by Zechiax** [comment]
Not intentional, thank you for the fix! I'll publish a new minor version to NuGet in a moment
